	<header>
		<div class="layout header">
			<h1 id="logo"><a href="http://bapquadgames.com/camelJS/"><img src="http://bapquadgames.com/camelJS/logo/cameljs.png" alt="camelJS" width="100" /></a></h1>
			<p id="menu-btn"><img alr="Menu" src="http://bapquadgames.com/camelJS/img/menu.gif" width="32" /></p>
			<nav>
				<ul>
					<li id="home"><a href="http://bapquadgames.com/camelJS/">HOME</a></li>
					<li id="dld"><a href="http://bapquadgames.com/camelJS/camel.js" download>DOWNLOAD</a></li>
					<li id="exm"><a href="http://bapquadgames.com/camelJS/Samples/">EXAMPLES</a></li>
					<li id="spp"><a href="#">TUTORIALS</a></li>
					<li id="ctt"><a href="http://bapquadgames.com/contact.html">CONTACTS</a></li>
					<li id="cll"><a href="javascript:void(0);">INDEX</a></li>
				<ul>
			</nav>
		</div>
	</header>